--- 
document:
  name: "Three-Year Plan for ICT"
  description: "The Three-Year Plan is a strategic and economic policy document for all Public Administrations that oversees the digital transformation of the country."
  tags: 
    - "piano triennale"
